networks:
  proxy:
    external: true
volumes:
  app-public:
services:
  db:
    hostname: demo-integ-db
    image: registry.projects.demo.fr/demo/system/citus-postgis:internal-todo
    env_file:
      - ./environment/db.env
    user: 1002:1002
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${STORAGE_DIRECTORY_PATH}/config/citus/docker-entrypoint-initdb.d/multi-databases.sh:/docker-entrypoint-initdb.d/multi-databases.sh
      - ${STORAGE_DIRECTORY_PATH}/data/postgres-data:/var/lib/postgresql/data
  typesense:
    hostname: demo-integ-typesense
    image: typesense/typesense:1-2-3
    env_file:
      - ./environment/typesense.env
    networks:
      - default
      - proxy
    ports:
      - 8108:8108
    depends_on: []
    volumes:
      - ${STORAGE_DIRECTORY_PATH}/data/typesense-data:/data
  minio:
  api:
    hostname: demo-integ-api
    image: demo/api:release/3-4-debug
    env_file:
      - .env
