networks:
  proxy:
    external: true
volumes:
  app-public:
services:
  nartex-integ-db:
    image: registry.projects.nartex.fr/nartex/system/citus-postgis:internal-todo
    env_file:
      - ./environment/db.env
    user: 1002:1002
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${STORAGE_DIRECTORY_PATH}/config/citus/docker-entrypoint-initdb.d/multi-databases.sh:/docker-entrypoint-initdb.d/multi-databases.sh
      - ${STORAGE_DIRECTORY_PATH}/data/postgres-data:/var/lib/postgresql/data
  nartex-integ-typesense:
    image: typesense/typesense:1-2-3
    env_file:
      - ./environment/typesense.env
    networks:
      - default
      - proxy
    ports:
      - 8108:8108
    "# commentaire":
      qqchose: autre
    depends_on: []
    volumes:
      - ${STORAGE_DIRECTORY_PATH}/data/typesense-data:/data
  api:
    image: realty/api:release/3-4-debug
    env_file:
      - .env
