name: Unit Test

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI Steps
        uses: ./.github/actions/ci-steps
